name: "Universal Changelog Generator"
description: "Unopinionated changelog for your conventional commits. Doesn't force you to use semver or any specific versioning strategy."
author: "Hrusikesh Panda <mrchief_2000@yahoo.com>"
branding:
  icon: "book"
  color: "blue"
inputs:
  previousReleaseTagNameOrSha:
    description: "Tag Name or SHA of previous release"
  nextReleaseTagName:
    description: "Tag Name of next release"
  nextReleaseName:
    description: "Friendly Name of next release"
  configFilePath:
    description: "Path to custom config (optional)"
    required: false
outputs:
  changelog:
    description: "Changelog in markdown format"
runs:
  using: "node12"
  main: "dist/index.js"
