name: CI

on:
  push:

jobs:
  ci:
    name: CI Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      - name: Install dependencies
        run: yarn install

      - name: Run Tests
        run: yarn test

      - name: Check build
        run: yarn build
